### ISSUE TITLE
2.6.0 release / django 2 support

### ISSUE THREAD

**Issue by kaiaeberli** [yourlabs/django-session-security#109]
after updating to Django 2.03 I get the following error:

  File "C:\ProgramData\Anaconda3\lib\site-packages\session_security\middleware.py", line 15, in <module>
    from django.core.urlresolvers import reverse, resolve, Resolver404
ModuleNotFoundError: No module named 'django.core.urlresolvers'

It seems this is an incompatibility, as urlresolvers was dropped.

**Comment by jpic** [comment]
Agreed, this should be made compatible, looking forward to merge a patch, will make a release then.

**Comment by kaiaeberli** [comment]
my bad - it works if i install the dev version

**Comment by jpic** [comment]
Thanks for your feedback, will make a release right away

**Comment by jpic** [comment]
Oh, we already have a 3.6.0-rc1 release, can you try it and let us know if it works for you I'll ditch the -rc1

pip install django-session-security==3.6.0-rc1

**Comment by JanMalte** [comment]
@jpic Caution: the new version is tagged with 3.6.0-rc1 on github, but published as 2.6.0-rc1 on pypi
https://github.com/yourlabs/django-session-security/releases/tag/3.6.0-rc1
https://pypi.python.org/pypi/django-session-security/2.6.0rc1

**Comment by jpic** [comment]
Thanks , removed 3.6.0-rc1 release and issued 2.6.0 !
