### ISSUE TITLE
Setting warning and expiration timeouts based on user pemissions

### ISSUE THREAD

**Issue by monty700** [yourlabs/django-session-security#115]
I've been using this package with success. It was very easy to install and use.

I'd like to set longer warning and expiration timeouts if the logged in user is staff (request.user.is_staff) or a superuser (request.user.is_superuser).

Is there any way to do this with the current version? If not, I would appreciate this enhancement.

**Comment by claytondaley** [comment]
see #107.  Is it no addressed?

**Comment by monty700** [comment]
Ah yes, thank you.
