### ISSUE TITLE
Django 2.1 & 2.2 compatibility?

### ISSUE THREAD

**Issue by jhancia** [yourlabs/django-session-security#125]
Is this package compatible with Django 2.1 & 2.2? Anyone using it in production? If so, we should add it to tox.ini and travis.yml

**Comment by aviars** [comment]
This package does nto work with Django 3.  results in `TemplateSyntaxError at /

'staticfiles' is not a registered tag library`

**Comment by its4net** [comment]
Not working for me in Django 2.2, any tips? I followed changes above. User get logged out after time regardless of activity and the popup warning never shows.

**Comment by JanMalte** [comment]
@its4net do you get any JavaScript errors in your browser debug console?

Did you included the `session_security/all.html` template?

And did you loaded jQuery in any way?
```html
    {# Load SessionSecurity javascript 'class', jquery should be loaded - by you - at this point #}
    <script type="text/javascript" src="{% static 'session_security/script.js' %}"></script>
```
