### ISSUE TITLE
Question about SESSION_SECURITY_INSECURE setting

### ISSUE THREAD

**Issue by marsvolta80** [yourlabs/django-session-security#126]
Good morning, 

I just wanted to get some clarification on the SESSION_SECURITY_INSECURE setting. Based on documentation it seems like if you set SESSION_EXPIRE_AT_BROWSE_CLOSE to True then you wouldn't need to set the SESSION_SECURITY_INSECURE setting? Also the documentation seems to suggest you wouldn't want to use this app without setting SESSION_EXPIRE_AT_BROWSER_CLOSE being set to True. Overall I was just a little confused on how this setting is used. Can you describe a scenario of how you would use this setting?

Thank you!

**Comment by claytondaley** [comment]
The package will [throw an exception](https://github.com/yourlabs/django-session-security/blob/119f055bc9a9a4d9977d891c5854ec85b931c6a5/session_security/settings.py#L54) if you don't do one of two things:

1. set SESSION_EXPIRE_AT_BROWSER_CLOSE
1. set SESSION_SECURITY_INSECURE

You absolutely should do the first, but a bypass exists if (for some reason?!?!) you needed to prevent this from happening (e.g. for testing or for a specific type of user).

**Comment by claytondaley** [comment]
If you have a suggestion on how to phrase it more clearly, you're welcome to submit a PR!
