### ISSUE TITLE
Can I override the templates?

### ISSUE THREAD

**Issue by sillycube** [yourlabs/django-session-security#128]
I found that the templates are located in /usr/local/lib/python3.7/site-packages. Can I override them with my custom templates instead of directly changing the templates under the folder?

**Comment by mpasternak** [comment]
No silly questions. Do you know how to {% extends %} a template?

**Comment by sillycube** [comment]
Yes, I know! Just looked at my code and it's basically similar to {% include %}!

**Comment by jpic** [comment]
You would need to change the template name in the include tag anyway,
unless you have that plugin that allows to extend a template of the same
name given an app name
