### ISSUE TITLE
session_security does not properly support django 4 - uses deprecated django.conf.urls lib

### ISSUE THREAD

**Issue by RustyTaint666** [yourlabs/django-session-security#155]
I recently upgraded a project to django 4.2, and now I am running into an import error in the session_security project. Here is the import error:
session_security\urls.py", line 18, in <module>
    from django.conf.urls import url
ImportError: cannot import name 'url' from 'django.conf.urls'

django.conf.urls has been deprecated and removed in django 4. Is there any way around this currently or is a code change required?

**Comment by mpasternak** [comment]
Patches accepted

**Comment by RustyTaint666** [comment]
The problematic import exists here: venv/Lib/site-packages/session_security/urls.py

**Comment by RustyTaint666** [comment]
I think that this file needs to be updated to support django 4: https://github.com/yourlabs/django-session-security/blob/master/session_security/urls.py

**Comment by RustyTaint666** [comment]
never mind. I think I see the correct import on master. weird. I have this version 2.6.7 installed

**Comment by RustyTaint666** [comment]
maybe something cached old lib. I will check. thank you for the quick response

**Comment by RustyTaint666** [comment]
yep. old lib was cached. my bad lol. thank you for the help.
