### ISSUE TITLE
Add the posivility of excluding some urls, from auto-closing

### ISSUE THREAD

**Issue by Viroide** [yourlabs/django-session-security#38]
The app work's great but I need to exclude some urls from closing. 

The project is a e-learning platform so it has perfect sence to close if the user is iddle for 5 minutes in the most of cases. But we have urls that display an audio, so the stundent can be listening the audio for more than 5 minutes. Is there any posivility to exclude them ? 

Thanks 4 the app

**Comment by jpic** [comment]
Maybe it would be easier to add a bit of code in the page which streams audio to extend the session. Would that work for you ?

**Comment by Viroide** [comment]
How could I do what ?

**Comment by jpic** [comment]
Just call `sessionSecurity.activity()` in js as much as needed. Maybe with a recursive `setTimeout()` callback or something.

**Comment by Viroide** [comment]
Thank you very much! 

It works perfectly!

**Comment by jpic** [comment]
You're welcome B)
