### ISSUE TITLE
What's the license on this library?

### ISSUE THREAD

**Issue by tmesquita** [yourlabs/django-session-security#47]
Just wondering what you are licensing this library under. Thanks

**Comment by luzfcb** [comment]
https://github.com/yourlabs/django-session-security/blob/stable/2.x.x/setup.py#L54

**Comment by tmesquita** [comment]
Ah, overlooked that line. Thanks!

**Comment by jpic** [comment]
WTFPL :D

On Tue, Jul 28, 2015 at 8:33 PM, Thomas <notifications@github.com> wrote:

> Ah, overlooked that line. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yourlabs/django-session-security/issues/47#issuecomment-125706178>
> .
>



-- 
http://yourlabs.org <http://blog.yourlabs.org>
Customer is king - Le client est roi - El cliente es rey.
