### ISSUE TITLE
Template incompatibility with Django 1.9a1

### ISSUE THREAD

**Issue by dpoirier** [yourlabs/django-session-security#53]
I'm starting to test our project that uses django-session-security with Django 1.9a1, and I run into a fatal error:

    django.template.exceptions.TemplateSyntaxError: 'url' is not a valid tag or filter in tag library 'future'

from session_security/templates/session_security/all.html

Changing this would not be compatible with Django 1.4, but anyone still stuck on 1.4 could override the template.

**Comment by eriktelepovsky** [comment]
+1

**Comment by jpic** [comment]
If you want to make a PR and deprecate up to version 1.8 (excluded) that's fine by me ;)

**Comment by skroth** [comment]
+1 would be nice, now that 1.9 is out

**Comment by eriktelepovsky** [comment]
There is a pull request #56

**Comment by jpic** [comment]
Compat with Django 1.9 and 1.10 was released in 2.3.1.
