### ISSUE TITLE
Different expire duration for each urls or user

### ISSUE THREAD

**Issue by Dean-Christian-Armada** [yourlabs/django-session-security#58]
Hi,

Is it possible to define duration for each url or user?

**Comment by jpic** [comment]
Not yet, but it's been priority #432153 for a lot of us I guess ;)

**Comment by Dean-Christian-Armada** [comment]
So will this be feature implemented?

**Comment by jpic** [comment]
The most accurate answer to this question is: maybe !

Will you make a PR for it ?

**Comment by Dean-Christian-Armada** [comment]
by PR you mean what?

**Comment by jpic** [comment]
Pull Request !​

**Comment by mjschultz** [comment]
I put up a PR that adds a `get_expire_seconds` method that takes in the request. In theory you could then make a simple subclass of the middleware and returns a custom value depending on the user/url/random digit/whatever.

**Comment by jpic** [comment]
Thanks for your contribution ! Keep up the great work :guitar: 

Released in 2.3.2
