### ISSUE TITLE
Not receiving expiry warning

### ISSUE THREAD

**Issue by freedomflyer** [yourlabs/django-session-security#64]
```
SESSION_COOKIE_AGE = 60
SESSION_SECURITY_WARN_AFTER = 10
SESSION_SECURITY_EXPIRE_AFTER = SESSION_COOKIE_AGE
```

Here are my settings, based on http://django-session-security.readthedocs.org/en/latest/full.html 

On my frontend, when I ping the server, I am correctly getting the number of seconds since session refresh, and I'm also receiving the logout message. However, I'm not receiving any sort of "warning" message. Why isn't this working?

**Comment by freedomflyer** [comment]
I am only using the django bit of the library. I'm using an Angular SPA on the frontend. So in Angular I am polling the /ping endpoint to get data about the session status. When I log to the console, I am getting something like:

```
1
2
3
4
5
...
...
...
60
logout
```

**Comment by jpic** [comment]
Warning display is entirely implemented on the client side, so you'll have
to show the warning yourself ;)

**Comment by freedomflyer** [comment]
Good to know. Thanks.

**Comment by jpic** [comment]
I'm all for including an Angular version upstream, there's no reason we
should support only jQuery.

The script is pretty straight forward, you should have no problem adapting
it:
https://github.com/yourlabs/django-session-security/blob/stable/2.x.x/session_security/static/session_security/script.js#L64
