### ISSUE TITLE
NoReverseMatch in Django 1.9 when DEBUG = True

### ISSUE THREAD

**Issue by tobias-9** [yourlabs/django-session-security#66]
I get the following error when switching to Django 1.9 with version 2.3.2:

NoReverseMatch: Reverse for 'session_security_ping' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []

I get this in my project when DEBUG is True, but suspect it could happen when False too.

The issue is that Django 1.9 now loads template tags early and while URL's are getting processed (also eary), django-session-security imports its settings, which in turn tries to resolve the session_security_ping url.

A simple fix would be to import the EXPIRE_AFTER and WARN_AFTER inside of the respective methods rather than at the module level.

**Comment by jpic** [comment]
Is it possible to reproduce this in the test_project ?

It works on Dj 1.9 here: https://travis-ci.org/yourlabs/django-session-security

**Comment by tobias-9** [comment]
Unfortunately, it looks like the test_project is not complete when I clone (eg, no urls.py).

Anyway, with my own VERY simple project with just django.contrib.admin and django-session-security installed and a very simple "home" TemplateView utilizing the session_security_tags, I do not get the NoReverseMatch exception.  However, if a breakpoint is set inside session_security/settings.py you will observe the issue when the PASSIVE_URLS is attempting to be set, but django/admin/sites.py (line 192 in Django 1.9.5) will silently mask this error in a simple project (seems things get loaded a second time around in DEBUG and things work themselves out).  In a more complex project, it would be hard to predict what might happen in between, which is what I am experiencing.

Again, this is just with DEBUG = True - it seems everything is fine with DEBUG = False.

In any event, thanks for putting this package together (and maintaining it!).

Cheers!

**Comment by jpic** [comment]
On Mon, Apr 25, 2016 at 7:53 PM, tobias-9 <notifications@github.com> wrote:

> Unfortunately, it looks like the test_project is not complete when I clone
> (eg, no urls.py).
>
> urls.py should be there but perhaps you haven't checked out the submodules
?

> Anyway, with my own VERY simple project with just django.contrib.admin and
> django-session-security installed and a very simple "home" TemplateView
> utilizing the session_security_tags, I do not get the NoReverseMatch
> exception. However, if a breakpoint is set inside
> session_security/settings.py you will observe the issue when the
> PASSIVE_URLS is attempting to be set, but django/admin/sites.py (line 192
> in Django 1.9.5) will silently mask this error in a simple project (seems
> things get loaded a second time around in DEBUG and things work themselves
> out). In a more complex project, it would be hard to predict what might
> happen in between, which is what I am experiencing.
>
Again, this is just with DEBUG = True - it seems everything is fine with
> DEBUG = False.
>
Could you upload your project source code and list the steps to reproduce
the issue ?

Please make it minimal

Cheers B)
