### ISSUE TITLE
Django Admin getting logged out automatically without warning

### ISSUE THREAD

**Issue by brunoprela** [yourlabs/django-session-security#70]
My team has successfully implemented session-security in our app. Users are alerted after a period of inactivity and then automatically logged out and redirected. However, session-security is causing our Admin site to be logged out of Django admin - even if there is activity - and no warning is given.

**Comment by jpic** [comment]
Perhaps session expires ?

**Comment by zhgabor** [comment]
i faced the same problem, seems that we have to include the JS in admin
but if i include 

`
{% block extrahead %}
    {% include 'session_security/all.html' %}
{% endblock %}
`

to admin base.html, it probably will work BUT on every page change it will alert a message something like: _you have unsaved changes, are you sure you want to leave the page?_

**Comment by jpic** [comment]
Could you reproduce this in the test_project somehow ?

Thx !

**Comment by zhgabor** [comment]
my scenario:
admin has django-suit, and some other apps running and it seems the problem is only on MY SIDE. :disappointed: it seems that the security template is not loaded at all in admin base.html -- i will have to check + fix 

test_project - works perfectly without any hickup :+1: with django-suit installed also

**Comment by santhosh432** [comment]
Try it ...it works for me ..
if Admin site to be logged out without warn .,, then needs to check jquery runtime in console (shift+F9), it may shows the $ not defined or sessionsecurity is not defined.

If there is an error like this ..

Needs to add Jquery library above  the {% include 'session_security/all.html' %} in base.html 

EX:


```
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
    {% include 'session_security/all.html' %}
    <script type="text/javascript">
    sessionSecurity.confirmFormDiscard = undefined;
    </script>
```
It worked for me ...
