### ISSUE TITLE
Security Issue Email

### ISSUE THREAD

**Issue by claytondaley** [yourlabs/django-session-security#74]
I'd like to report what I view as a vulnerability, but don't see a dedicated email for this sort of correspondence.  Please let me know how you'd like me to report it.

**Comment by jpic** [comment]
Thanks for your feedback @claytondaley , send me an email at jamespic on gmail and if anybody else is interrested please let me know.

Perhaps we should consider moving to gitlab which has a feature for security issues.

**Comment by jpic** [comment]
We now have a security email: 84393c108f554e789c22386199e92dbad6f302df

The use case you reported is double fixed by 52d531928fd5e84a1dceaf0bc8ca47beefc52523 and #77 also incoming.

Thanks for your feedback !

:guitar:

**Comment by jpic** [comment]
Both fixes were released in 2.4.0.
