### ISSUE TITLE
Release for Django 1.10 support?

### ISSUE THREAD

**Issue by lynnco** [yourlabs/django-session-security#83]
My project uses your package and it would be great to have a release with this PR! https://github.com/yourlabs/django-session-security/pull/81 

(Just wanted to makes this as a tracking issue, or ping yall in case it slipped someone's mind!)

**Comment by jhancia** [comment]
Would also love a new release here.  Thanks :)

**Comment by RohitTalwalkar** [comment]
Same here!

**Comment by jpic** [comment]
2.4.1 released !
