### ISSUE TITLE
Post-logout redirect never fires

### ISSUE THREAD

**Issue by shacker** [yourlabs/django-session-security#93]
I was planning to submit a PR here today, but I've hit a roadblock. Setup:

We use django_cas_ng and our users auth against a CAS SSO system. When they click the Logout link on our site, they are logged out of the site AND redirected to our campus SSO system's logout page, which kills their ticket. This is important, especially for multi-user lab computers.

After installing django-session-security, clicking the Logout link manually still works normally. But if I let a user time out with DSS, they are logged out but they are NOT redirected to the SSO logout view. They stay on the site. In this state, the user can click the Login link again and be logged in automatically again **without** having to authenticate (because the CAS session ticket is still alive). That's bad.

So I started a PR that lets the dev set a custom logout URL. If present, the middleware.py adds a simple redirect after `logout()`:

1) 
```
        if delta >= timedelta(seconds=expire_seconds):
            logout(request)
            return HttpResponseRedirect(settings.LOGOUT_REDIRECT_URL)
```

(this is in `process_request()`). The problem is that the redirect never happens after timeout - the user is logged out but the page is not redirected to `settings.LOGOUT_REDIRECT_URL`. I don't understand why. 

If I modify it to go to the CAS logout page without performing an internal logout first:

2) 
```
        if delta >= timedelta(seconds=expire_seconds):
            return HttpResponseRedirect(settings.LOGOUT_REDIRECT_URL)
```

Then a timeout logout *does* redirect, but if the user then tries to go back to the site (e.g. to log in as someone else), they're stuck in a loop eternally handing off to settings.LOGOUT_REDIRECT_URL, so they can't access the site at all. 

I can't seem to make this work either way. Any idea what I'm missing here? It seems clear that No. 1 is what I want, but I can't figure out why the redirect never fires. 

n.b. I also have code to call django_cas_ng's `logout()` function rather than Django's, but that doesn't affect the problem - it's the same either way.

**Comment by jpic** [comment]
> (this is in process_request()). The problem is that the redirect never happens after timeout - the user is logged out but the page is not redirected to settings.LOGOUT_REDIRECT_URL. I don't understand why.

Perhaps because it's an ajax request ? Maybe the fix also involves a tiny bit of JS ;)

I'm not really sure about problem 2, perhaps an example app in the test project would help ?

**Comment by shacker** [comment]
Maybe I'm not following how this works - are you saying that this python is converted to ajax? Our logout system is not doing any ajax. 

Not sure we need a full test app here - testing is as simple as adding one line to middleware.py:

```
        if delta >= timedelta(seconds=expire_seconds):
            print("About to log out")
            logout(request)
            print("Just logged out")
```

Then let it time out. The first print statement will fire, the second will not. Or am I misunderstanding?

**Comment by jpic** [comment]
Perhaps logout raises an exception that is later caught ?

No ajax ? Have you seen this ?
https://github.com/yourlabs/django-session-security/#how-does-it-work-

**Comment by shacker** [comment]
Ah, I wasn't clear whether you were suggesting that our SSO logout app was ajax-based or whether you meant the ajax aspects of DSS. I'm aware that DSS is doing ajax exchange, but it's not doing it *at this point in the code*, which is all Python, right? 

So it's still not clear to me - why doesn't any python after `logout()` fire here? Is there another way I can handle this?

**Comment by shacker** [comment]
Django's auth.logout() does not swallow exceptions, nor does django_cas_ng's, and we've never had a problem with logout crashing. There are no 500s in runserver console or in browser console indicating any problem there, so I don't think logout is raising an exception.

**Comment by jpic** [comment]
K, can you use a debugger like pdb and step in logout to discover where it
goes

**Comment by shacker** [comment]
OK, I've just had a very long session trying to debug this. Starting with pdb in middleware.py, then injecting pdb -  and print statements -  directly into Django's logout function, stepping through with n, then a much deeper dive with s, watching every step of the way and trying to figure out where it's going wrong. I just cannot figure out where it's getting derailed.  No errors - It just doesn't redirect. 

To simplify, I'm leaving django_cas_ng out of the picture and just dealing with django's logout function. 

I then tried another approach. Realized that you're doing:

`from django.contrib.auth import logout`
but if you use the other logout:
`from django.contrib.auth.views import logout`

you can pass in `next_page='http://example.com'`

So rather than 

```
from django.contrib.auth import logout
logout(request)
return HttpResponseRedirect('http://example.com')
```

I tried:

```
from django.contrib.auth.views import logout
logout(request, next_page="http://example.com")
```

No difference - same problem. 

To make sure there is nothing odd going on in my somewhat complex project, I then did a fresh pip install into a new/clean Django project, and tried the same modifications to middleware.py. Same results. 

This is a weird one. Quite a rabbit hole, and I'm running out of ideas. 

Are you able to reproduce this?

**Comment by shacker** [comment]
FWIW here's the tail end of a pdb session, just before and after where it claims to be doing the redirect:

```
> /path/to/python3.5/http/cookies.py(430)OutputString()
-> for key, value in items:
(Pdb) 
--Return--
(Pdb) > /path/to/venv/lib/python3.5/site-packages/django/contrib/staticfiles/handlers.py(63)__call__()-><HttpResponse...u/cas/logout">
-> return self.application(environ, start_response)

> /path/to/python3.5/http/cookies.py(431)OutputString()
-> if value == "":
(Pdb) 
(Pdb) > /path/to/python3.5/wsgiref/handlers.py(138)run()
-> self.finish_response()

> /path/to/python3.5/http/cookies.py(432)OutputString()
-> continue
(Pdb) 
(Pdb) [22/Mar/2017 14:33:37] "GET /session_security/ping/?idleFor=25&_=1490216704426 HTTP/1.1" 302 0
--Return--
> /path/to/python3.5/wsgiref/handlers.py(138)run()->None
-> self.finish_response()

> /path/to/python3.5/http/cookies.py(430)OutputString()
-> for key, value in items:(Pdb) 
[22/Mar/2017 14:33:38] "GET /people/ HTTP/1.1" 200 59895

```

**Comment by shacker** [comment]
To be clear on my goal here: If I can successfully call django_cas_ng's logout() function, it should handle the redirect. But I can't call it, just as I can't call Django's own logout func. The experiments above with manual redirects are because I'm trying alternative approaches.

**Comment by shacker** [comment]
We're going to to take another approach to this and not use django-session-security, but thanks for your time. 

I'm still curious about the solution to this if anyone is able to figure it out.

**Comment by santosh9991** [comment]
@shacker: I have the same issue. django_cas_ng logout doesn't get fired on Ajax request on timeout.
We use angular JS, django-1.9.7 and CAS for authentication. We wanted to include auto logout functionality .I have read through the comments. However, I coudn't figure-out the solution. I was wondering whether you found a solution. I have tried debugging in many ways. It works on on-click though. Can you please respond. Any suggestions are appreciated.

**Comment by claytondaley** [comment]
If you call `logout` from a view, you would normally return the [response](https://github.com/django/django/blob/adcf823359d7402fc1f57a2e005cea52905d897d/django/contrib/auth/views.py#L129) (links to an older version of Django because the interface recently changed).  I'm reasonably confident that this response conveys redirect information.  As you saw, the middleware does not return the response.  All it does is trigger the database-side processing for the logout.

But the "answer" isn't to change session security because the application cannot be responsible for timing out the SSO credential... the SSO server needs to do that.  Consider the simplest case:

 - User A logs into the application
 - User A closes the browser window holding the application (there's no opportunity to redirect, even if supported)
 - User B opens a new window and goes to email

Because User A's SSO session is still alive, they're routed to the user's email.  There's nothing that session security can do to take care of this.  The SSO server needs to timeout the SSO session.

The application *also* needs a timeout so application sessions don't outlast the SSO sessions (by more than the timeout), but session security already handles this.

**Comment by santosh9991** [comment]
@claytindaley: 
Thanks for taking your precious time and responding back.
Thanks for above mentioned solution. I have couple of questions on the suggestions you made above:
1.Will the user be logged out abruptly after the timeout('X' amount of time) configured in SSO server. For example, if user A is logged in and he has been using the application for 10 mins. Would the User A be logged out after 10 minutes session time, abruptly even if the User A is using the application continuously?   
 Below is my actual issue that I am concerned about:
1. cas_logout view is successfully called by Ajax http get request on timeout. However, user is not logged out. On page reload, user would automatically logged in.
 My understanding was, when ever cas_logout view is called user should be logged out and redirected to cas login page.
2.Same view when called using href(i.e on-click of sign-out button manually), it works perfectly fine. user is logged-out and redirected to cas login page
My question is why does the same view behave differently, when fired through Ajax http call and on-click (through href).

**Comment by santosh9991** [comment]
![image](https://user-images.githubusercontent.com/16803672/32921204-444a0552-caf2-11e7-9c0f-fa819edcd862.png)

**Comment by claytondaley** [comment]
Let me start by clarifying that I don't use CAS so I'm referring to SSO principles in general.

The application probably works one of two ways (determined by the plugin that manages Django auth):

1. It authenticates once (initially) - you will remain logged into the application so long as you don't timeout within the application
1. It reauthenticates periodically - if the SSO session ends, you will be prompted to re-authenticate at some point

However, you would expect the timer on the SSO session to be reset each time the application reauthenticates.  It follows that you shouldn't be abruptly terminated by either approach (unless the SSO timeout is shorter than the application reauth time).

**Comment by claytondaley** [comment]
> cas_logout view is successfully called by Ajax http get request on timeout. However, user is not logged out. On page reload, user would automatically logged in

Can you screenshot the logout call that that works?  The screenshot you provided shows a 403 (permission denied) error.  I assume the logout wasn't successful (which would explain why the subsequent login worked).  Compare the two URLs and make sure they are exactly the same.

**Comment by santosh9991** [comment]
![image](https://user-images.githubusercontent.com/16803672/32923145-8c8669a6-cafb-11e7-8167-5b6302a58af7.png)
Fig 1: server logs when ajax call fired when application auto-timed-out.
Above figure shows the server logs of the automatic Ajax request made after application session timeout. 
   
![image](https://user-images.githubusercontent.com/16803672/32923324-8f51bf90-cafc-11e7-850c-76b188d6fd59.png)
Fig 2: logs in the browser for logout call that "doesn't" works.

![image](https://user-images.githubusercontent.com/16803672/32923451-4dd9ef50-cafd-11e7-8fc5-6f1f187a464c.png)
Fig 3: server logs for logout call that works(manually hitting a sign-out button).

![image](https://user-images.githubusercontent.com/16803672/32923563-d753353e-cafd-11e7-84fd-38df7f9bfdf4.png)
Fig 4: Part of controller code where django_cas_ng logout is called automatically on application session timeout.


![image](https://user-images.githubusercontent.com/16803672/32923612-24fd088c-cafe-11e7-9f8e-3cb7612e8214.png)
Fig 5: Part of HTML code where same view is invoked using href.

When request comes through the href, as shown in Fig 5, user logs out and redirected to cas login page. On the other hand, when request fired using Ajax http, as shown in Fig 4, I face the issue(Fig 1 and 2).

**Comment by santosh9991** [comment]
Please ignore CAS Middleware and some other print statements. I have added print statements for debugging.

**Comment by claytondaley** [comment]
If you're using Chrome's developer tools, use this option to retain a log of all of the redirects during a logout:

![image](https://user-images.githubusercontent.com/1097439/32926114-09bc0d2c-cb0b-11e7-8fc9-fc2369bdab8e.png)

Click the manual logout button and screenshot the entry that successfully logs the user out of the SSO server.  I want to confirm that you don't get a 403 on that redirect... and hopefully you can compare the URL and find a difference.

**Comment by claytondaley** [comment]
I assume the two 403 calls are against the IP/domain of your SSO server, but maybe you should verify that as well.

**Comment by santosh9991** [comment]
{'issue_data':[]}
I tried, no luck. get the same response.
![image](https://user-images.githubusercontent.com/16803672/32966442-6986e27e-cb9f-11e7-8005-398116496703.png)

**Comment by claytondaley** [comment]
Oh I assumed that was the AJAX not the logout button.  So that's what happens when you press logout... and the user is successfully logged out?  Or that's what happens when you press the logout button and it doesn't work?

**Comment by santosh9991** [comment]
This happens when AJAX call is made from front end after timeout(Auto time-out), Ref. Fig:4 which I had mentioned in previous comments.
![image](https://user-images.githubusercontent.com/16803672/32968237-25a6fb0a-cba6-11e7-8e60-dba96faf2719.png)
Fig6: Browser logs for AJAX request. 
User logs out perfectly fine when logout button is pressed manualy.

**Comment by claytondaley** [comment]
> User logs out perfectly fine when logout button is pressed manualy.

Yes.  I'm asking you to snapshot the browser history when the user manually logs out.  I want to compare those calls to the AJAX calls.  I'm betting something is different.

**Comment by santosh9991** [comment]
![image](https://user-images.githubusercontent.com/16803672/32968978-d91ec54e-cba8-11e7-8f3b-0367385bed56.png)

**Comment by claytondaley** [comment]
Can you scroll up and find the call to the actual SSO server?  The tail end of the logs look to be the information about the current page (js libraries and such).

**Comment by claytondaley** [comment]
You're looking for a call like you see in the AJAX... something like "logout/?service="

**Comment by santosh9991** [comment]
![image](https://user-images.githubusercontent.com/16803672/32969094-5fdd03d4-cba9-11e7-8da2-007eb0ce1dc6.png)
Fig: Server logs

**Comment by claytondaley** [comment]
I mean scroll up in the browser history... in the chrome developer tools window you just screenshoted.

**Comment by santosh9991** [comment]
SSO logs are not saved for some reason in browser

**Comment by santosh9991** [comment]
![image](https://user-images.githubusercontent.com/16803672/32969347-62a64638-cbaa-11e7-814b-84257db0c2ff.png)
No logs are shown in the chrome browser when user logs out(on-click through href, Ref Fig 5 in above comments) without any issues. I see browser logs as mentioned in Fig 6. when user does not logout on AJAX call(Ref code in Fig. $)

**Comment by claytondaley** [comment]
> No logs are shown in the chrome browser when user logs out(on-click through href, Ref Fig 5 in above comments) without any issues.

You should at least see the call to URLs like (obviously using your domain/IP) `djangoapp.com/logout` followed by `ssoserver.com/login`  Try this sequence (leaving preserve logs on):

 - log into your application
 - click "clear" logs
   ![image](https://user-images.githubusercontent.com/1097439/32969882-4ec99460-cbac-11e7-936c-7cd03629cf22.png)
 - click logout link in app
 - (once the browser gets to the login screen) scroll to the absolute top of your chrome history and screenshot

You should definitely see at least the call to `djangoapp.com/logout` followed by some sequence that ends at `ssoserver.com/login`.

**Comment by santosh9991** [comment]
I followed the steps you have mentioned above. 
1. when I logged in I saw some XHR requests
![image](https://user-images.githubusercontent.com/16803672/32972735-6d41d63e-cbb9-11e7-8125-559eeefdf478.png)
Fig 8: browser logs when logged in
2.cleared browser logs
![image](https://user-images.githubusercontent.com/16803672/32972763-9518ce2e-cbb9-11e7-82e2-32deedbf097a.png)
Fig 9: cleared browser logs
3. Clicked on logout button
![image](https://user-images.githubusercontent.com/16803672/32972788-ba55a8d8-cbb9-11e7-95fe-9233db6a07be.png)
Fig 10: Logout button on application
4.When logged out of the application, all browsing logs were cleared automatically and login screen showed up.
![image](https://user-images.githubusercontent.com/16803672/32972985-a549d652-cbba-11e7-8351-382b58959bcd.png)
Fig 11: Browser logs after logout(empty)

**Comment by claytondaley** [comment]
You need to disable the filter.  You see the red filter icon:

![image](https://user-images.githubusercontent.com/1097439/32973148-9e4645c4-cbbb-11e7-802f-ae36b687d019.png)

It's happening because you've clicked "XHR".  If you unclick that icon (XHR or the filter entirely), you should get a full history.

**Comment by santosh9991** [comment]
![image](https://user-images.githubusercontent.com/16803672/32973304-524ae7dc-cbbc-11e7-9d6d-a91adda0ee1b.png)
Fig 12: Browser logs on successful logout

**Comment by claytondaley** [comment]
That says "login".  Any chance you didn't clear the logs before clicking logout?

**Comment by santosh9991** [comment]
![image](https://user-images.githubusercontent.com/16803672/32973423-fa756c48-cbbc-11e7-8ac1-57c02393193b.png)

**Comment by santosh9991** [comment]
![image](https://user-images.githubusercontent.com/16803672/32973636-3629139c-cbbe-11e7-973d-39d4b374bb32.png)

**Comment by claytondaley** [comment]
Perfect so you can see that the URLs are different.

**Comment by claytondaley** [comment]
Oh wait my bad.

**Comment by santosh9991** [comment]
![image](https://user-images.githubusercontent.com/16803672/32973855-bd322878-cbbf-11e7-8410-c12109270c6c.png)
Fig 13: Detail of the error

**Comment by claytondaley** [comment]
The only difference I see is xhr vs. text/html.  A quick search for 403 on xhr led me to this SO question:

https://stackoverflow.com/a/36816541/1978687

I'm not sure if this is your actual problem, but it aligns with the issue you describe.  If your request doesn't include headers that identify your SSO account, there's no way to log you out.

**Comment by claytondaley** [comment]
Hmm.  It looks like there are some headers in your Can you compare the headers in the successful and unsuccessful request and see if there are any differences?

**Comment by santosh9991** [comment]
You mean request headers?

**Comment by claytondaley** [comment]
Yes.  The SO question was suggesting that an XHR request may not carry the right headers.  That seemed like the next most-obvious thing to compare.  I'd look at the headers first and then the cookies.  If you were missing authentication information in one of these places, it would explain your issue.

**Comment by jpic** [comment]
Otherwise did you try debugging the logout view ? You could also print the request headers from there.

**Comment by claytondaley** [comment]
This is starting to sound like a CSRF (cross site request forgery) issue.  You're allowed to send the request using the browser, but prohibited from sending the request using JavaScript.

**Comment by santosh9991** [comment]
@claytondaley : As you mentioned, it should be with the request header. Below are the screen shots of request headers for AJAX and normal href(onclick request) browser logs
![image](https://user-images.githubusercontent.com/16803672/32974656-83dddea4-cbc5-11e7-94c8-559c874028a1.png)
Fig 15: request header for AJAX call(which we have issue with)
![image](https://user-images.githubusercontent.com/16803672/32974686-b53125ba-cbc5-11e7-962f-9cc1027e8c5d.png)
Fig 16: request header through on-click logout(which works fine)

**Comment by claytondaley** [comment]
Fig 16 says it's "login" not logout

**Comment by santosh9991** [comment]
my bad

![image](https://user-images.githubusercontent.com/16803672/32974875-a9a16ffa-cbc7-11e7-8d19-c906b4e5cbb2.png)
Fig 17: request header through on-click logout(which works fine)

**Comment by santosh9991** [comment]
@claytondaley : I tried replacing the context-type and datatype in the AJAX call, but no luck
![image](https://user-images.githubusercontent.com/16803672/32975001-9960bf32-cbc8-11e7-9be7-348b4adad56c.png)


Fig 19: Modified AJAX call code

**Comment by claytondaley** [comment]
OK.  It looks like the cookies are missing from the one that fails.  That makes sense as authentication information is often carried in cookies.

**Comment by santosh9991** [comment]
![image](https://user-images.githubusercontent.com/16803672/32984631-c0f936b2-cc6f-11e7-9715-939a0a42bdd0.png)
Fig 20: browser logs when I replace the AJAX content-Type to "application/json; charset=utf-8"

**Comment by santosh9991** [comment]
![image](https://user-images.githubusercontent.com/16803672/32984669-8a4b7160-cc70-11e7-97f6-248f517acb52.png)
Fig 21: Request header logs in browser for AJAX logout request after autotimeout

**Comment by claytondaley** [comment]
I don't think the content type is what matters.  I think you need to get the cookies into the request.  For CSRF reasons, I'm not sure the browser will ever do so automatically.  I suggest trying to replace the AJAX call with a [full page redirect](https://stackoverflow.com/questions/4744751/how-do-i-redirect-with-javascript).

**Comment by santosh9991** [comment]
![image](https://user-images.githubusercontent.com/16803672/32984702-009001ba-cc71-11e7-8aaa-21b7609d0beb.png)
@claytondaley : You want me to include cookies in the AJAX request

**Comment by claytondaley** [comment]
> You want me to include cookies in the AJAX request

I think it's failing because the authentication cookies are missing.  Even if you wanted to fix it, I'm not sure if you have access to the right cookies in your JavaScript (for security reasons).  If you can get the right cookies and get them included... that would be great.

If you can't, I'm suggesting changing the way the redirect is handled.

**Comment by claytondaley** [comment]
> If you can't, I'm suggesting changing the way the redirect is handled.

If this solves your issue, we may want to consider a change to session security, but I'd want you to confirm that it's working for you first.

**Comment by santosh9991** [comment]
@claytondaley : You are awesome man! It worked! Words are not enough to thank you. Can you please send your email id and linked in id to santu1santosh@gmail.com. We will be in touch.
![image](https://user-images.githubusercontent.com/16803672/32985060-4b144420-cc77-11e7-8ab0-4fbaa6aa93ea.png)

**Comment by claytondaley** [comment]
> What changes should be made?

I'm honestly not sure.  If you look [here](https://github.com/yourlabs/django-session-security/blob/master/session_security/static/session_security/script.js#L57), there's already code to do a full page redirect.  If `this.returnToUrl` was set to your logout page, it seems like it should be working fine.

Can you show me the code where you instantiate the sessionSecurity JS script?  For example:

```
{% include 'session_security/all.html' %}
```

or

```
        <script type="text/javascript">
            var sessionSecurity = new yourlabs.SessionSecurity({
                pingUrl: '{% url 'session_security_ping' %}',
                warnAfter: {{ request|warn_after|unlocalize }},
                expireAfter: {{ request|expire_after|unlocalize }},
                confirmFormDiscard: "{% trans 'You have unsaved changes in a form of this page.' %}"
            });
        </script>
```

**Comment by claytondaley** [comment]
@jpic, do we need to add `returnToUrl: ...` [here](https://github.com/yourlabs/django-session-security/blob/master/session_security/templates/session_security/all.html#L28)?  That may explain why the OP complained that:

> the page is not redirected to `settings.LOGOUT_REDIRECT_URL`

Obviously, the SSO server should also have a timeout, but it definitely sounds like the OP was properly configured for the behavior he (and @santosh9991) needs.

**Comment by jpic** [comment]
You're making it happen <3

**Comment by claytondaley** [comment]
@santosh9991 can you try the code in PR #101.  All you should need to do is add the setting `SESSION_SECURITY_REDIRECT_TO_LOGOUT = True`

**Comment by santosh9991** [comment]
@claytondaley  Will try and let you know

**Comment by claytondaley** [comment]
@santosh9991 Don't bother testing yet.  I got around to writing a test case and have some issues.  I'll let you know when they're resolved and push an update.

**Comment by claytondaley** [comment]
OK test cases now pass so @santosh9991, you should be good to go.  You'll need to add `SESSION_SECURITY_REDIRECT_TO_LOGOUT = True` to your application settings, but the code in the PR should do the rest of the work for you.

**Comment by santosh9991** [comment]
@claytondaley : Is the latest build available on pip? if not, can you please guide me where to pull the code from.

**Comment by claytondaley** [comment]
If you pull from https://github.com/claytondaley/django-session-security you should get a `redirect-to-logout` branch.  That's the PR branch.

**Comment by claytondaley** [comment]
@santosh9991 Did you test the PR?  Did it work?  If so, please let us know so we can consider merging it.

**Comment by santosh9991** [comment]
@claytondaley : It worked in the production. Thank you for the help.

**Comment by jpic** [comment]
This has been merged to master
